name: state_provider
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  #State management
  stacked: ^3.5.0
  rxdart: ^0.28.0
  #Local data storage
  hive: ^2.2.3
  #Secure Storage to store encrypt key
  flutter_secure_storage: ^10.0.0
  #Localization
  easy_localization: ^3.0.0
  page_transition: ^2.1.0
  cupertino_icons: ^1.0.8
  #Provide app path
  path_provider: ^2.1.5
  sqlcipher_flutter_libs: ^0.6.8
  simple_animations: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.30.1
  build_runner: ^2.10.5
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: grandview
      fonts:
        - asset: assets/fonts/Grandview.ttf
        - asset: assets/fonts/GrandviewLight.ttf
          weight: 200
        - asset: assets/fonts/GrandviewBold.ttf
          weight: 700
    - family: hanuman
      fonts:
        - asset: assets/fonts/HanumanRegular.ttf
scripts:
  clean: >
    flutter clean;
    flutter pub get;
  build: flutter pub run build_runner build
  run_uat: flutter run -t lib/main_uat.dart
  run_prod: flutter run -t lib/main_prod.dart
